using Limekuma.Prober.Common;
using System.Collections.Frozen;

namespace Limekuma.Utils;

public static class ConstantMap
{
    public static readonly FrozenDictionary<string, FrozenSet<string>> VersionMap = new Dictionary<string, FrozenSet<string>>
    {
        ["真"] = ["maimai", "maimai PLUS"],
        ["超"] = ["maimai GreeN", "GreeN"],
        ["檄"] = ["maimai GreeN PLUS", "GreeN PLUS"],
        ["橙"] = ["maimai ORANGE", "ORANGE"],
        ["晓"] = ["maimai ORANGE PLUS", "ORANGE PLUS"],
        ["桃"] = ["maimai PiNK", "PiNK"],
        ["樱"] = ["maimai PiNK PLUS", "PiNK PLUS"],
        ["紫"] = ["maimai MURASAKi", "MURASAKi"],
        ["堇"] = ["maimai MURASAKi PLUS", "MURASAKi PLUS"],
        ["白"] = ["maimai MiLK", "MiLK"],
        ["雪"] = ["maimai MiLK PLUS", "MiLK PLUS"],
        ["辉"] = ["maimai FiNALE", "FiNALE"],
        ["熊"] = ["maimai でらっくす", "舞萌DX"],
        ["华"] = ["maimai でらっくす", "舞萌DX"],
        ["爽"] = ["maimai でらっくす Splash", "舞萌DX 2021"],
        ["煌"] = ["maimai でらっくす Splash", "舞萌DX 2021"],
        ["宙"] = ["maimai でらっくす UNiVERSE", "舞萌DX 2022"],
        ["星"] = ["maimai でらっくす UNiVERSE", "舞萌DX 2022"],
        ["祭"] = ["maimai でらっくす FESTiVAL", "舞萌DX 2023"],
        ["祝"] = ["maimai でらっくす FESTiVAL", "舞萌DX 2023"],
        ["双"] = ["maimai でらっくす BUDDiES", "舞萌DX 2024"],
        ["宴"] = ["maimai でらっくす BUDDiES", "舞萌DX 2024"],
        ["镜"] = ["maimai でらっくす PRiSM", "舞萌DX 2025"],
        ["彩"] = ["maimai でらっくす PRiSM", "舞萌DX 2025"],
        ["舞"] = [
            "maimai",
            "maimai PLUS",
            "maimai GreeN",
            "maimai GreeN PLUS",
            "maimai ORANGE",
            "maimai ORANGE PLUS",
            "maimai PiNK",
            "maimai PiNK PLUS",
            "maimai MURASAKi",
            "maimai MURASAKi PLUS",
            "maimai MiLK",
            "maimai MiLK PLUS",
            "maimai FiNALE",
            "GreeN",
            "GreeN PLUS",
            "ORANGE",
            "ORANGE PLUS",
            "PiNK",
            "PiNK PLUS",
            "MURASAKi",
            "MURASAKi PLUS",
            "MiLK",
            "MiLK PLUS",
            "FiNALE",
        ],
        ["霸"] = [
            "maimai",
            "maimai PLUS",
            "maimai GreeN",
            "maimai GreeN PLUS",
            "maimai ORANGE",
            "maimai ORANGE PLUS",
            "maimai PiNK",
            "maimai PiNK PLUS",
            "maimai MURASAKi",
            "maimai MURASAKi PLUS",
            "maimai MiLK",
            "maimai MiLK PLUS",
            "maimai FiNALE",
            "GreeN",
            "GreeN PLUS",
            "ORANGE",
            "ORANGE PLUS",
            "PiNK",
            "PiNK PLUS",
            "MURASAKi",
            "MURASAKi PLUS",
            "MiLK",
            "MiLK PLUS",
            "FiNALE",
        ]
    }.ToFrozenDictionary();

    public static readonly FrozenDictionary<Ranks, (float, float, float)> RatingMap = new Dictionary<Ranks, (float, float, float)>
    {
        [(Ranks)14] = (101, 0.224f, 15),
        [Ranks.SSSPlus] = (100.5f, 0.224f, 15),
        [Ranks.SSS] = (100, 0.216f, 14),
        [Ranks.SSPlus] = (99.5f, 0.211f, 13),
        [Ranks.SS] = (99, 0.208f, 12),
        [Ranks.SPlus] = (98, 0.203f, 11),
        [Ranks.S] = (97, 0.2f, 10),
        [Ranks.AAA] = (94, 0.168f, 9.4f),
        [Ranks.AA] = (90, 0.152f, 9),
        [Ranks.A] = (80, 0.136f, 8),
        [Ranks.BBB] = (75, 0.12f, 7.5f),
        [Ranks.BB] = (70, 0.112f, 7),
        [Ranks.B] = (60, 0.96f, 6),
        [Ranks.C] = (50, 0.8f, 5),
        [Ranks.D] = (0, 0.64f, 4),
    }.ToFrozenDictionary();
}